function [startOffset,endOffset,hp1,hp2,cqp1,cqp2,Directory,Experiment,dataFile,whichDate] = google(startOffset,endOffset,hp1,hp2,cqp1,cqp2)
rtFolder='C:\Users\Owner\Dropbox (BEC)\BECteam\Jin\google\';
%list subfolders under google 
subFolder = {'sri-ipb2-27b\2-heaterpow-only'...
             'sri-ipb2-27b\3-qpow8hours'...
             'sri-ipb2-27b\4-qpow-heaterpow-83ns'...
             'sri-ipb2-27b\7-qpow-heaterpow-100ns'...
             'sri-ipb2-27b\qpow-heatpower125w'...
             'sri-ipb2-27b\q-calibration'...
             'sri-ipb2-27b\DC-cali2'...
             'ipb3-32b'...
             'ipb1_30b\6-qpow-only'...
             'ipb1_30b\DC-calibration'...
             'ipb1_30b\5-heaterpower-only'...
             'ipb1_30b\DC-cali2'...
             'ipb1_30b\DC-temp-control'...
             'ipb1_30b\DC-temp-control-12212016'...
             'ipb1-29b\ipb1-29b-he-DC'...
             'ipb1-29b\ipb1-29b-h2-DC'...
             };
Directory=char(strcat(rtFolder,subFolder(15)));
AllFiles = getall(Directory);  %SORTED BY DATE....
whichDate = 'dc-29b-he';
dataFile =Directory;
switch (whichDate)
case 'dc-29b-he'   
    hp1 = 0;
    hp2= 60;
    Experiment = AllFiles(1:3);            
end  
end
