% Initial housekeeping
clear; close all; clc
addpath('C:\jinwork\BE\matlab')
addpath('C:\jinwork\BE\matlab\addaxis5')
%Control parameters
qPlot = false;
dcPlot = false;
tempExpFit = false;
hpExpFit = false;
writeOutput = true;
plotOutput = true;
errorBarPlot = false;
findDuplicates = false;
%plot bounds setting
coreRes = 0.5;
startOffset = 0;
endOffset = 0;
hp1 = 0;
hp2 = 40; 
qp1 = 5;
qp2 = 55;
cqp1 = 0;
cqp2 = 12;
%analyzeSet
reactors = {'ipb1-29',...
            'ipb1-30'...
            'sri-ipb2-27'...
            'ipb3-32'...
            'google'...
            'ipb3-36b'};
field = 1;
analyzeSet = table([3; 3], [4; 6], ['12092016'; '12312016'],[4; 16], [5; 16],'VariableName',{'reactor','folder','runDate','startF','endF'});
value = {'ipb3 dc he vs h2';analyzeSet};
c(1,:) = {'ipb3 dc he vs h2',analyzeSet};
c(2,:) = {'ipb3 dc he vs h2',analyzeSet};
t=c(1,2)
for ai = 1:size(analyzeSet)
 ri = analyzeSet(ai,1)
 fi  = analyzeSet(ai,2)
 rdi = analyzeSet(ai,3);
 startF = analyzeSet(ai,4);
 endF = analyzeSet(ai,5);
reactor =3;
%list reactors and cores
switch (reactor)
case 1   
    [startOffset,endOffset,hp1,hp2,cqp1,cqp2,Directory,Experiment] = ipb1_29(folder,runDate,startF,endF,startOffset,endOffset,hp1,hp2,cqp1,cqp2);
case 2
    folder = 2;
    runDate = '01112017'; 
    [startOffset,endOffset,hp1,hp2,cqp1,cqp2,Directory,Experiment] = ipb1_30(folder,runDate,startF,endF,startOffset,endOffset,hp1,hp2,cqp1,cqp2); 
case 3
    folder = 4;
    runDate = '01112017'; 
    [startOffset,endOffset,hp1,hp2,cqp1,cqp2,Directory,Experiment] = sri_ipb2_27(folder,runDate,startF,endF,startOffset,endOffset,hp1,hp2,cqp1,cqp2);
case 4
    folder = 6;
    runDate = '01102017';
    [startOffset,endOffset,hp1,hp2,cqp1,cqp2,Directory,Experiment] = ipb3_32(folder,runDate,startF,endF,startOffset,endOffset,hp1,hp2,cqp1,cqp2); 
case 5
    [startOffset,endOffset,hp1,hp2,cqp1,cqp2,Directory,Experiment] = google(folder,runDate,startF,endF,startOffset,endOffset,hp1,hp2,cqp1,cqp2);     
end
Experiment'
loadHHT 
%SeqStepNum = SeqStep0x23; clear SeqStep0x23
QPulseLengthns = QPulseLength0x28ns0x29; clear QPulseLength0x28ns0x29
plotTitle =strcat(Directory,runDate); 
%change datetime to number
dateN=datenum(DateTime,'mm/dd/yyyy HH:MM:SS');
rawData = horzcat(dateN,...
     SeqStepNum,...
     HeaterPower,...
     CoreTemp,...
     InnerBlockTemp1,...
     OuterBlockTemp1,...
     QPulseLengthns,...
     CoreQPower,...
     CoreQV1Rms,...
     CoreQV2Rms,...
     QSupplyPower,...
     QCur,...
     QSupplyVolt,...
     QSetV,...
     QKHz,...
     QPow,...
     TerminationHeatsinkPower,...
     QPulsePCBHeatsinkPower,...
     CalorimeterJacketFlowrateLPM,...
     QPCBHeatsinkFlowrateLPM,...
     TerminationHeatsinkFlowrateLPM,...
     CalorimeterJacketPower,...
     CalorimeterJacketH2OInT,...
     CalorimeterJacketH2OOutT,...
     QPCBHeatsinkH2OInT,...
     QPCBHeatsinkH2OOutT,...
     TerminationHeatsinkH2OInT,...
     TerminationHeatsinkH2OOutT,...
     QPulseVolt,...
     PressureSensorPSI);
     %HydrogenValves);
%asignColumn name 
rawDataN = dataset({rawData,'dateN',...
     'SeqStepNum',...
     'HeaterPower',...
     'CoreTemp',...
     'InnerBlockTemp1',...
     'OuterBlockTemp1',...
     'QPulseLengthns',...
     'CoreQPower',...
     'CoreQV1Rms',...
     'CoreQV2Rms',...
     'QSupplyPower',...
     'QCur',...
     'QSupplyVolt',...
     'QSetV',...
     'QkHz',...
     'QPow',...
     'TerminationHeatsinkPower',...
     'QPulsePCBHeatsinkPower',...
     'CalorimeterJacketFlowrateLPM',...
     'QPCBHeatsinkFlowrateLPM',...
     'TerminationHeatsinkFlowrateLPM',...
     'CalorimeterJacketPower',...
     'CalorimeterJacketH2OInT',...
     'CalorimeterJacketH2OOutT',...
     'QPCBHeatsinkH2OInT',...
     'QPCBHeatsinkH2OOutT',...
     'TerminationHeatsinkH2OInT',...
     'TerminationHeatsinkH2OOutT',...
     'QPulseVolt',...
     'PressureSensorPSI'});
     %'HydrogenValves'}); 
%filter rawData out 
dataSize = size(rawData,1);
%find duplicated
if findDuplicates
  duplicates(coreTemp);
end
%show startOffset and endOffset
DateTime(1+int16(startOffset*360))
DateTime(end - int16(endOffset*360))
rawData = rawData(1+int16(startOffset*360):end-int16(endOffset*360),:);
%rawData(any(isnan(rawData)),:)=[]; %take out rows with Nan
%(isnan(j1)) = -2 ;
rawData = rawData(rawData(:,2) > 0,:); %only process data with seq
dataSize = size(rawData,1)
dt = datetime(dateN, 'ConvertFrom', 'datenum') ;
if dcPlot
  plotDC(dt,hp1,hp2,rawDataN,plotTitle);   
end 
if qPlot
  plotQ(dt,hp1,hp2,qp1,qp2,cqp1,cqp2,coreRes,rawDataN,plotTitle);  
end 
if writeOutput 
 writeOut(rawDataN, reactor, reactors, runDate, hpExpFit, tempExpFit);
end 
end
