#Brillouin Energy Isoperibolic Data processor
#This scripts purpose is to look at data files generated by theIsoperibolic Hydrogen 
#Hot Tube Reactor, with ine data set from when the Reactor is run with Helium and
#the other set of data are run when the reactor contains Hydrogen.
#The idea is to use the Helium data as a control, and compare it with the 
#Hydrogen at the same temperature, pressure, and Q pulse stimulation parameters.

#To do this we will use the Plyr and ggplot2 packages.

#first thing we need to is read in the data. The data is in CSV format. Make the working
#directory the directory that contains the data

library(plyr)
library(ggplot2)

Helium_File = "IPB2_H2_180psig_650C_EDITED.csv"
Hydrogen_File = "IPB2_Q_seq_50V_step_He_650C_day-01.csv"
Q_Parameters<-c("Q.N.Pulses","Q.kHz","Q.Pulse.Length..ns.","Q.Supply.Volt")


df_Helium = read.csv(Helium_File, header = TRUE, sep = ",", quote = "\"",dec = ".", fill = TRUE)
df_Hydrogen = read.csv(Hydrogen_File, header = TRUE, sep = ",", quote = "\"",dec = ".", fill = TRUE)





Calc_Non_Heater_Power <- function(Heater_Pow,Calorimetry_Pow) {
  l=length(Heater_Pow)
  x<-Heater_Pow[10:l]
  y<-Calorimetry_Pow[10:l]
  mean(y-x)
}

Remove_Heater_Off_Data <- function(df) {
  subset(df,Heater.Enable==1 & Heater.Power>0)
}

Remove_Q_Off_Data <- function(df) {
  subset(df,Q.Enable==1 & Q.Supply.Volt > 0)
}

#Remove_Transient_Data <- 

Round_Voltage <-function(df) {
  #round the power supply voltage to nearest multiple of ten, because the setpoint is not recorded
round((df$Q.Supply.Volt)/10)*10
}


Parse_Time_String <- function(df){
  as.POSIXct(df$Date...Time,tz="","%m/%d/%Y %H:%M:%S")
}

Reaction_Heat <- function(df){
  
}


#strptime(df$Date...Time,"%m/%d/%Y %H:%M:%S")


df_Hydrogen<-Remove_Heater_Off_Data(df_Hydrogen)
df_Hydrogen<-Remove_Q_Off_Data(df_Hydrogen)
df_Hydrogen$Q.Supply.Volt<-Round_Voltage(df_Hydrogen)
df_Hydrogen$Date...Time<-Parse_Time_String(df_Hydrogen)

df_Helium<-Remove_Heater_Off_Data(df_Helium)
df_Helium<-Remove_Q_Off_Data(df_Helium)
df_Helium$Q.Supply.Volt<-Round_Voltage(df_Helium)
df_Helium$Date...Time<-Parse_Time_String(df_Helium)


df1 <- ddply(df_Helium,Q_Parameters,summarize,q_plus_rxn_heat=Calc_Non_Heater_Power(Heater.Power,Isoperibolic.Calorimetry.Power))
df1$gas<-rep("He",nrow(df1))

df2 <-ddply(df_Hydrogen,Q_Parameters,summarize,q_plus_rxn_heat=Calc_Non_Heater_Power(Heater.Power,Isoperibolic.Calorimetry.Power))
df2$gas<-rep("H2",nrow(df2))

df3<-df1
df3$gas<-NULL
colnames(df3)[5]<-"Excess Heat"

for(i in 1:nrow(df1))
{
  #there is a better way to this next line, but have not figured it out yet
  x<-df1[i,]$q_plus_rxn_heat- df2[df2$Q.N.Pulses==df1[i,1] & df2$Q.kHz==df1[i,2] & df2$Q.Pulse.Length..ns.==df1[i,3] & df2$Q.Supply.Volt==df1[i,4],]$q_plus_rxn_heat
  df3[[i,5]]<-x
}



x
#plot(df_Qpow_in_core_He$Q.Pulse.Length..ns.,df_Qpow_in_core_He$q_in_core)
#plot(df_Hydrogen$Date...Time,df_Hydrogen$Heater.Power)
#ggplot(df_Helium,aes(x=Date...Time))+geom_line(aes(y=Isoperibolic.Calorimetry.Power),color="red")+
#  geom_line(aes(y=Heater.Power),color="blue")+geom_line(aes(y=Q.Pow),color="green")
