%clean  
QPulseLengthns = QPulseLength0x28ns0x29; clear QPulseLength0x28ns0x29
power = 'q';
if isDC
  power = 'dc';
end  
plotTitle =strcat(tmpDir,'-',runDate,'-',power,'-',gas); 
size(dateN)
DateTime(end)
%change datetime to number
rawData = horzcat(dateN,...
     SeqStepNum,...
     CoreHtrPow,...
     CoreReactorTemp,...
     InnerCoreTemp,...
     QPulseLengthns,...
     QKHz,...
     QPow,...
     TerminationThermPow,...
     CoreGasIn,...
     CoreGasOut,...
     H2MakeupLPM,...
     PowOut,...
     CoreResistance...
);
size(rawData)

%show startOffset and endOffset
size(DateTime)
%DateTime(1+int16(startOffset*360))
%DateTime(end - int16(endOffset*360))
DateTime(end)
size(DateTime)
n1 = int16(startOffset*360);
n2 =int16(endOffset*360);
if n1 + n2 > 0  %work around
rawData = rawData(1+n1:end-n2,:);
end
%(isnan(j1)) = -2 ;
rawData = rawData(rawData(:,2) > 0,:); %only process data with seq
%rawData(any(isnan(rawData)),:)=[]; %take out rows with NaN but not a good code
%rawData(any(isnan(rawData),2),:)=[];
%asignColumn name 
size(rawData)
rawDataN = dataset({rawData,'dateN',...
     'SeqStepNum',...
     'HeaterPower',...
     'CoreTemp',...
     'InnerCoreTemp',...
     'QPulseLengthns',...
     'QKHz',...
     'QPow',...
     'TerminationThermPow',...
     'CoreGasIn',...
     'CoreGasOut',...
     'H2MakeupLPM',...
     'PowOut',...
     'CoreResistance'});
     %'HydrogenValves'}); 
dt = datetime(rawDataN.dateN, 'ConvertFrom', 'datenum') ;
if tsPlot
  plotConflatTS_temp(dt,hp1,hp2,temp1,temp2,rawDataN,plotTitle,pos,figname);
end 
